repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.2
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.3.2
        files: "(mcp-bridge/.*\\.(ts|js|json|md)|src/.*\\.(md))"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.57.0
          - @typescript-eslint/parser@7.16.1
          - @typescript-eslint/eslint-plugin@7.16.1
        files: "mcp-bridge/.*\\.(ts|tsx|js|jsx)"
        args: ["--ext", ".ts,.tsx,.js,.jsx"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: ".*\\.(yml|yaml)$"
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ".*\\.(sh|bash)$"
  - repo: https://github.com/aquasecurity/trivy
    rev: v0.52.2
    hooks:
      - id: trivy-config
        files: "(docker-compose\\.yml|.*\\.(yaml|yml))"
  - repo: https://github.com/anchore/syft
    rev: v1.5.0
    hooks:
      - id: syft
        args: ["packages", "--scope", "all-layers", "--file", "sbom/sbom-spdx.json"]
        stages: ["manual"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
