services:
  third-eye-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  mcp-bridge:
    build:
      context: .
      dockerfile: docker/Dockerfile.mcp
    environment:
      - API_URL=http://third-eye-api:8000
    depends_on:
      - third-eye-api
    ports:
      - "7331:7331"
