image:
  repository: registry.aliyun.com/third-eye/api
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
ingress:
  enabled: false

postgres:
  enabled: true
  image: postgres:16-alpine
  storageClassName: standard
  storage: 10Gi
  username: third_eye
  password: change-me
  database: third_eye
