apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "third-eye.fullname" . }}
  labels:
    {{- include "third-eye.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      {{- include "third-eye.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "third-eye.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: third-eye-secrets
