{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "third-eye.fullname" . }}-postgres
  labels:
    {{- include "third-eye.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "third-eye.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
