name: CI

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun run typecheck || tsc --noEmit

      - name: Lint
        run: bun run lint || echo "Lint not configured"

      - name: Unit tests
        run: bun test

      - name: Build server
        run: bun build --target bun ./apps/server/src/start.ts --outdir dist

      - name: Setup Node.js for Next.js build
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build UI
        run: |
          cd apps/ui
          npm ci
          npm run build

  e2e:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright
        run: bunx playwright install --with-deps chromium

      - name: Seed database
        run: bun run setup

      - name: Run E2E tests
        run: bun run e2e
        env:
          CI: true

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: apps/ui/test-results/

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker compose -f docker/docker-compose.yml build

      - name: Test Docker stack
        run: |
          docker compose -f docker/docker-compose.yml up -d
          sleep 10
          curl --fail http://localhost:7070/health || exit 1
          docker compose -f docker/docker-compose.yml down
